config/routes.rb
PromptCloud::Application.routes.draw do
  resources :customers
  root :to => 'welcome#index'

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  before_save :modifi_data_format

  attr_accessible :pic,:data_schema, :attach, :brief_details, :company_name, :contact_number, :contact_person_name, :crawl_frequency, :data_format, :email_id, :project_name, :seed_url
  has_attached_file :pic, :styles =>{ :medium => "300x300>", :thumb => "100x100>" }
  has_attached_file :attach


  validates :brief_details, length: { minimum: 4, maximum: 500 }
  validates :company_name, length: { minimum: 4, maximum:20 }
  validates :contact_number,numericality: true
  validates :contact_person_name, length:{ minimum: 4, maximum:20 }
  validates :crawl_frequency,numericality: true
  validates :data_format, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email_id, presence: true,
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  validates :project_name, length: { minimum: 4, maximum:20 }
  validates :seed_url, presence: true





  def modifi_data_format
    a = self.data_format.to_a
    self.data_format = []
    a.each do |i|
      self.data_format << i if ! i.empty?
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @customers }
    end
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
    @customer = Customer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @customer }
    end
  end

  # GET /customers/new
  # GET /customers/new.json
  def new
    @customer = Customer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @customer }
    end
  end

  # GET /customers/1/edit
  def edit
    @customer = Customer.find(params[:id])
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(params[:customer])

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render json: @customer, status: :created, location: @customer }
      else
        format.html { render action: "new" }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /customers/1
  # PUT /customers/1.json
  def update
    @customer = Customer.find(params[:id])

    respond_to do |format|
      if @customer.update_attributes(params[:customer])
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy

    respond_to do |format|
      format.html { redirect_to customers_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/customers/_form.html.erb
<div class="modal-body row-fluid">
  <div class="span6">
    <%= form_for @customer, :html => { :multipart => true } do |f| %>
        <% if @customer.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

              <ul>
                <% @customer.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
        <% end %>


        <h3>Customer Information</h3>
        <div class="field" style="color: #76D2F6">
          <%= f.label :contact_person_name %><br />
          <%= f.text_field :contact_person_name, :required => true%>
        </div>
        <div class="field"style="color: #76D2F6">
          <%= f.label :company_name %><br />
          <%= f.text_field :company_name, :required => true %>
        </div>
        <div class="field"style="color: #76D2F6">
          <%= f.label :email_id %><br />
          <%= f.text_field :email_id, :required => true %>
        </div>
        <div class="field" style="color: #76D2F6">
          <%= f.label :contact_number %><br />
          <%= f.number_field :contact_number, :required => true %>
        </div>
  </div>
  <div class="span6">
    <h3>Project Information</h3>
    <div class="field" style="color: #76D2F6">
      <%= f.label :project_name %><br />
      <%= f.text_field :project_name, :required => true %>
    </div>
    <div class="field" style="color: #76D2F6">
      <%= f.label :brief_details %><br />
      <%= f.text_area :brief_details, :required => true %>
    </div>
    <div class="field" style="color: #76D2F6">
      <%= f.label :seed_url %><br />
      <%= f.text_field :seed_url, :required => true %>
    </div>
    <div style="color: #76D2F6">
      <%= f.label :data_format %>
      <%= f.select :data_format, [['PDF', 'PDF'], ['XML', 'XML'], ['JSON', 'JSON'],['CSV','CSV'],['XLSX','XLSX']], {}, :multiple => true, :required => true %>
    </div>
    <div class="field" style="color: #76D2F6">
      <%= f.label :crawl_frequency %><br />
      <%= f.number_field :crawl_frequency, :required => true %>
    </div>

    <div class="field" style="color: #76D2F6">
      <%= f.label :data_schema %><br />
      <%= f.text_area :data_schema %>
    </div>


    <p style="color: #76D2F6">
      <b> attachment </b><br/>
      <%= f.file_field :attach %>
    </p>

    <p style="color: #76D2F6">
      <b> Picture </b><br/>
      <%= f.file_field :pic %>
    </p>
    <div class="actions" style="color: #76D2F6">
      <%= f.submit %>
    </div>
    <% end %>
  </div>
</div>

</div>

app/views/customers/edit.html.erb
<body style="background-color: gainsboro;">
<div class = "container">
<h1>Editing customer</h1>

<%= render 'form' %>
<div style="padding-left: 178px">
<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>
</div>
</div>
</body>

app/views/customers/index.html.erb
<body style="background-color: gainsboro;">

<h1>Listing customers</h1>


<div class="table table-bordered">
  <table class="table" >
  <tr style="color: #76D2F6">
    <th>Contact person name</th>
    <th>Company name</th>
    <th>Email</th>
    <th>Contact number</th>
    <th>Project name</th>
    <th>Brief details</th>
    <th>Seed url</th>
    <th>Data format</th>
    <th>Crawl frequency</th>
    <th>File attached</th>
    <th>Picture</th>
    <th></th>
  </tr>

<% @customers.each do |customer| %>
  <tr>
    <td><%= customer.contact_person_name %></td>
    <td><%= customer.company_name %></td>
    <td><%= customer.email_id %></td>
    <td><%= customer.contact_number %></td>
    <td><%= customer.project_name %></td>
    <td><%= customer.brief_details %></td>
    <td><%= customer.seed_url %></td>
    <td><%= customer.data_format %></td>
    <td><%= customer.crawl_frequency %></td>
    <td><%= customer.attach.url%></td>
    <td><%= customer.pic.url(:medium)%></td>
    <td><%= link_to 'Show', customer %></td>
    <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
    <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>
</div>
<br />

<%= link_to 'New Customer', new_customer_path %>

</body>

app/views/customers/new.html.erb
<html>
<head>
</head>
<body style="background-color: gainsboro;">

<div class="container">
  <h1 style="color: #76D2F6">New Customer</h1>

  <%= render 'form' %>

</div>
<div style="padding-left: 178px">
  <%= link_to 'Back', customers_path %>
</div>
</body>
</html>

app/views/customers/show.html.erb
<html>
<head>
  <style>
  p{
  line-height:35px;
  }
  </style>
</head>
<body style="background-color: gainsboro;">
    <div class="container">
        <h1>Customer Details</h1>

        <p id="notice"><%= notice %></p>

        <p>
          <b style="color: #76D2F6">Contact person name:</b>
          <%= @customer.contact_person_name %>
        </p>

        <p>
          <b style="color: #76D2F6">Company name:</b>
          <%= @customer.company_name %>
        </p>

        <p>
          <b style="color: #76D2F6">Email:</b>
          <%= @customer.email_id %>
        </p>

        <p>
          <b style="color: #76D2F6">Contact number:</b>
          <%= @customer.contact_number %>
        </p>

        <p>
          <b style="color: #76D2F6">Project name:</b>
          <%= @customer.project_name %>
        </p>

        <p>
          <b style="color: #76D2F6">Brief details:</b>
          <%= @customer.brief_details %>
        </p>

        <p>
          <b style="color: #76D2F6">Seed url:</b>
          <%= @customer.seed_url %>
        </p>

        <p>
          <b style="color: #76D2F6">Data format:</b>
          <%= @customer.data_format %>
        </p>

        <p>
          <b style="color: #76D2F6">Crawl frequency:</b>
          <%= @customer.crawl_frequency %>
        </p>

        <p>
          <b style="color: #76D2F6">Data Schema:</b>
          <%= @customer.data_schema %>
        </p>

        <a href="<%= @customer.attach.url %> ">
          <b style="color: #76D2F6"> File attached </b>
        </a>
        <br>
        <p>
          <b style="color: #76D2F6">Image:</b>
        <%= image_tag @customer.pic.url(:medium) %>
        </p>
        <br>
        <%= link_to 'Edit', edit_customer_path(@customer) %> |
        <%= link_to 'Back', customers_path %>
    </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PromptCloud</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PromptCloud</title>
</head>

<body style="background-color: #000000">
<div class="index-back">
<div class = "promptcloud-title" style="height:auto; width:auto; max-width:300px; max-height:300px;">
<%= link_to (image_tag "pc-logo.png"),{:controller => "customers", :action => "new"} %>
</div>
</div>
</body>

</html>